# config.yaml

# Setting Parameters
settings:
  model_type: 'yolov10n'
  dataset: 'sample_dataset'

# ClearML Settings
clearml:
  project_name: 'YOLOv10 Training'
  task_name_format: '%Y-%m-%d-%H-%M'

# Training Parameters
training:
  epochs: 150
  imgsz: 640
  batch: 0.92
  cache: true
  workers: 12
  label_smoothing: 0.1
  close_mosaic: 50
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mixup: 0.0

# Model Parameters
model:
  data_dir: './datasets/{dataset}'
  train_images_dir: 'train/images'
  train_labels_dir: 'train/labels'
  val_images_dir: 'valid/images'
  val_labels_dir: 'valid/labels'
  test_images_dir: 'test/images'
  test_labels_dir: 'test/labels'
  classes: ['class1', 'class2', 'class3', 'class4', 'class5']

# Export Parameters
export:
  format: 'onnx'
  optimize: true
  half: false
  nms: true
  int8: true
